// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenConfigDir() {
  return window['go']['main']['App']['OpenConfigDir']();
}

export function OpenSelectM3U8() {
  return window['go']['main']['App']['OpenSelectM3U8']();
}

export function OpenSelectTsDir(arg1) {
  return window['go']['main']['App']['OpenSelectTsDir'](arg1);
}

export function StartMergeTs(arg1) {
  return window['go']['main']['App']['StartMergeTs'](arg1);
}
