// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenConfigDir():Promise<string>;

export function OpenSelectM3U8():Promise<string>;

export function OpenSelectTsDir(arg1:string):Promise<Array<string>>;

export function StartMergeTs(arg1:main.MergeFilesConfig):void;

export function TaskAdd(arg1:main.ParserTask):Promise<Error>;
