// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTasks() {
  return window['go']['app']['App']['ClearTasks']();
}

export function Open(arg1) {
  return window['go']['app']['App']['Open'](arg1);
}

export function OpenConfigDir() {
  return window['go']['app']['App']['OpenConfigDir']();
}

export function OpenSelectM3U8() {
  return window['go']['app']['App']['OpenSelectM3U8']();
}

export function OpenSelectTsDir(arg1) {
  return window['go']['app']['App']['OpenSelectTsDir'](arg1);
}

export function Play(arg1) {
  return window['go']['app']['App']['Play'](arg1);
}

export function RemoveTaskNotifyItem(arg1) {
  return window['go']['app']['App']['RemoveTaskNotifyItem'](arg1);
}

export function SniffLinks(arg1) {
  return window['go']['app']['App']['SniffLinks'](arg1);
}

export function StartMergeTs(arg1) {
  return window['go']['app']['App']['StartMergeTs'](arg1);
}

export function TaskAdd(arg1) {
  return window['go']['app']['App']['TaskAdd'](arg1);
}

export function TaskAddMuti(arg1) {
  return window['go']['app']['App']['TaskAddMuti'](arg1);
}
